name: staticrypt
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  staticrypt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Encrypt docs example with StatiCrypt
        env:
          REGISTRY: ghcr.io
          ORG: royfrancis
          IMAGE: staticrypt:3.5.4
          STATICRYPT_PASSWORD: ${{ secrets.STATICRYPT_PASSWORD }}
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/home/work \
            ${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.IMAGE }} \
            site -r \
            --directory docs/ \
            --config false

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


